name: Publish to Homebrew

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Homebrew cask tag to bump'
        required: true
        type: string

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: eugenesvk/action-homebrew-bump-cask@a05fd49892799eade237259963d787ba0143dab1 #3.8.5
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          cask: kameleo
          tag: ${{ inputs.version || github.ref }}
