name: Publish to Homebrew
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu
    steps:
      - uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{secrets.HOMEBREW_TOKEN}}
          cask: kameleo
